Repository ezsystems/ezplatform-ee, pull requests merged in 2019-12, with the labels that each got.

#114 EZEE-2907: Removed dependency to flex-workflow
  composer.json
  config/bundles.php
  config/routes/ezplatform_flex_workflow.yaml
Labels: Improvement, Ready for review

#119 [Behat] Removed FlexWf suite
  behat.yml.dist
Labels: Ready for review

#120 fix: Removed ezsystems/repository-forms package from composer.json
  composer.json
Labels: Bug, Ready for review
