Repository ezsystems/ezplatform-ee, pull requests merged in 2020-03, with the labels that each got.

#127 EZEE-2911: Added routes, database and cache configuration needed by Site Factory
  composer.json
  config/bundles.php
  config/packages/cache.yaml
  config/packages/doctrine.yaml
  config/packages/ezplatform.yaml
  config/routes/ezplatform_site_factory.yaml
Labels: Feature

#130 Added basic SiteFactory configuration for Behat env
  config/packages/behat/ez_platform_site_factory.yaml
  config/packages/behat/ezplatform.yaml
Labels: Ready for review

#132 Added default configuration for a Site Factory
  config/packages/behat/ezplatform_site_factory.yaml
  config/packages/ezplatform_site_factory.yaml
Labels: QA approved
