Repository ezsystems/ezplatform-ee, pull requests merged in 2020-06, with the labels that each got.

#141 Update cache_pool comment in ezplatform.yaml
  config/packages/ezplatform.yaml
Labels: Ready for review

#140 EZEE-2497: Enabled Ajax Captcha routing file
  app/config/routing.yml
Labels: QA approved

#144 Enabled ezsystems/ezplatform-elastic-search-engine
  composer.json
  config/bundles.php
  config/packages/ezplatform_elastic_search_engine.yaml
Labels: Feature

#147 Exposed ELASTICSEARCH_DSN env variable
  .env
  config/packages/ezplatform_elastic_search_engine.yaml
Labels: Improvement
