Repository ezsystems/ezplatform-ee, pull requests merged in 2020-10, with the labels that each got.

#156 Enabled ezsystems/ezplatform-connector-dam
  composer.json
  config/bundles.php
  config/routes/ezplatform_connector_dam.yaml
Labels: Ready for QA

#157 EZEE-3224: Added ezplatform-segmentation package
  composer.json
  config/bundles.php
  config/routes/ibexa_platform_segmentation.yaml
Labels: Feature, Ready for review

#160 EZEE-2817: Added behat suite for ezplatform-page-fieldtype
  behat.yml.dist
Labels: Feature, Ready for review

#148 [Platform.sh]: ElasticSearch support
  .platform.app.yaml
  .platform/services.yaml
  config/packages/overrides/platformsh.php
Labels: Improvement

#162 [Platform.sh] Avoid recreating ES mappings on each deploy
  .platform.app.yaml
Labels: QA approved
